services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/tcp'
      - '7777:7777/udp'
      - '8888:8888/tcp'
    volumes:
      - './satisfactory-server:/config'
    environment:
      - MAXPLAYERS=6
      - PGID=1000
      - PUID=1000
      - STEAMBETA=true
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 4G
